a = int(input('insira o primeiro numero '))
b = int(input('insira o segundo numero '))
c = int(input('insira o terceiro numero '))
x1=((b*b)-(4*a*c))
print (x1)
x0 = ((-b + (x1 ** (1/2)))/(2*a)) 
print(x0)
x2 = ((-b - (x1 ** (1/2)))/(2*a))
print(x2)